### ISSUE TITLE
Bug in event generation no.2

### ISSUE THREAD

**Issue by ghost** [TokTok/apidsl#3]
Code generation fails with error: `` Fatal error: exception Failure("...: error at TYPEDEF") `` If no comment is supplied before keyword typedef in event {} scope.

**Comment by iphydf** [comment]
This is WAI, but the error message is terrible. This is mostly due to bad tooling (menhir). I will look into using better tooling later on.

**Comment by iphydf** [comment]
I won't be able to improve tooling for this anytime soon. OCaml parser generators are decades behind everybody else (which is strange, for a language used so much in compilers and static analysers).
